import Head from "next/head";

export default function Article({ post }) {
  console.log(post);
  return (
    <>
      <Head>
        <title>Article | {post.title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="row text-center">
        <div className="col-md-12">
          <h4>{post.title}</h4>

          <p className="my-3">{post.body}</p>
        </div>
      </div>
    </>
  );
}

export async function getStaticProps(context) {
  const id = context.params.article

  const res = await fetch(`https://jsonplaceholder.typicode.com/posts/${id}`)

  const post = await res.json()

  return { props: { post } }
}

export async function getStaticPaths() {
  const res = await fetch(
    `https://jsonplaceholder.typicode.com/posts?_start=0&_limit=10`
  );

  const posts = await res.json();

  const paths = posts.map((post) => ({
    params: { article: post.id.toString() },
  }));

  return { paths, fallback: false }
}
